<?php
namespace Yauc;

define('APP_ROOT', __DIR__.DIRECTORY_SEPARATOR.'..');
define('VIEW_DIR', APP_ROOT.DIRECTORY_SEPARATOR.'View'.DIRECTORY_SEPARATOR);

require APP_ROOT.DIRECTORY_SEPARATOR.'vendor'.DIRECTORY_SEPARATOR.'autoload.php';
